---
title: "hw1"
author: "Ken"
date: "2023-10-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
```

# Question Two: A
```{r questionTwoA}
iris <- read.csv("iris.csv")
histogram <- hist(iris$Petal.Length,
                  breaks=seq(0,8,l=17),
                  main="Petal Lengths of Setosas, Virginicas, and Versicolors",
                  xlab="Petal Lengths (in cm)",
                  ylab="Frequency")
```

The shape of the histogram is bimodal. The percentage of iris flowers with a petal length less than or equal to 2cm is .3267. 

# Question Two: B
```{r questionTwoB}
setosas <- iris %>% filter(iris$Species == "setosa")
setosa_hist <- hist(setosas$Petal.Length,
                  breaks=seq(0,8,l=17),
                  main="Petal Lengths of Setosas",
                  xlab="Petal Lengths (in cm)",
                  ylab="Frequency")

virginicas <- iris %>% filter(iris$Species == "virginica")
virginica_hist <- hist(virginicas$Petal.Length,
                  breaks=seq(0,8,l=17),
                  main="Petal Lengths of Virginicas",
                  xlab="Petal Lengths (in cm)",
                  ylab="Frequency")

versicolors <- iris %>% filter(iris$Species == "versicolor")
versicolor_hist <- hist(versicolors$Petal.Length,
                  breaks=seq(0,8,l=17),
                  main="Petal Lengths of Versicolors",
                  xlab="Petal Lengths (in cm)",
                  ylab="Frequency")

```

